### PR TITLE
Rebuild to pull in latest GSL

### PR DESCRIPTION
**Pull request by kdm9**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Thanks for opening this PR @kdm9 - I'm not sure how to proceed from here? I'm happy to open a different PR if that's easier than debugging what's happening here?

**Comment by kdm9** [comment]
@jeromekelleher good question. AFAICT, the only build failures are on OSX, and are actually "deprecation brownouts", i.e. they forced them to fail as those CI configs will soon be removed.

The original problem is that the C module is linked to libgsl.so.25 (gsl version 2.6) but the version requirement is for version 2.7 and therefore only libgsl.so.26 is installed. I'm hoping a rebuild triggered by bumping the version number will fix this, and has for other packages where I've found this issue. I've hit this same problem in quite a few different packages now, so maybe @conda-forge/gsl have ideas on how to prevent this more thoroughly than just rebuilding with every new gsl version.

If you were to just merge this, I *think* what will happen is that we'll get new packages for windows & linux, but mac will still have the old ones as the CI builds aren't working. I don't know if any folks from the conda-forge org can comment on the osx CI issue (e.g. @conda-forge/help-osx-arm64).

**Comment by isuruf** [comment]
> [Re-rendered](https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks) with the latest conda-smithy (Use the phrase @conda-forge-admin, please rerender in a comment in this PR for automated rerendering)

Are you sure this was done?

**Comment by jeromekelleher** [comment]
Everything is building now, so merging.

**Pull request merged**
